name: Testing

on:
  push:
    branches:
    - issue-*
    - milestone-*
    - project-*

jobs:
  Perl-0000:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mysql
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v1
    - name: Setup Git User
      run: git config --global user.name "Al Newkirk"
    - name: Setup Git Email
      run: git config --global user.email "awncorp@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.user ${{ secrets.GithubToken }}
    - name: Install CPANM
      run: sudo apt install -y cpanminus
    - name: Install Perl::Critic
      run: sudo cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: sudo cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
        TESTDB_INITIAL: mysql
        TESTDB_DATABASE: zing
        TESTDB_HOSTNAME: 127.0.0.1
        TESTDB_HOSTPORT: 3306
        TESTDB_USERNAME: root